### ISSUE TITLE
Re-organise code

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1675]
Code organisation. We have some giant dumping grounds of "stuff". It's not in a position where it can really be released to the community.

- [x] Rename `TxData` to `TxBody` (#1837)
- [x] Split apart `LedgerState` (#2894)
- [x] Split apart and document the `SetAlgebraInternals` (#2564)
