### ISSUE TITLE
Conway translate era

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3160]
The translate era instance for Conway needs to be adapted to the new transaction body.

Notable details:

- [x] we should reject transactions with MIR certs. this will probably just be done automatically by the deserializer, making use of the versioned CBOR.
- [x] ~translate pointer addresses to enterprise addresses. See this [discussion](https://github.com/cardano-foundation/CIPs/pull/374/files#r1026688534).~ New plan, leave pointers be, but do not allow them to be used for staking. Also translate bogus pointers to zero values. Fixed in #3360 and #3253
- [x] - provide values to new protocol parameters using the conway config/genesis. Fixed in #3499 
- [x] - also get rid of TxOuts from the UTxO with zero ADA. Fixed in #3530

**Comment by lehins** [comment]
Fixed in #3499 

Providing removed fields in the transaction (such as MIR/GenDeleg certificates and update field) will be rejected by the `translateEraThroughCBOR` function
