### ISSUE TITLE
Fix CDDL for transaction witnesses

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3922]
Current binary format for witnesses has some issues:

* It allows duplicates, which are just discarded
* It uses list syntax, where all of them are either sets or maps
* Fields are optional, but they are also allowed to be empty 

We need to solve all of those issues in Conway mostly in a backwards compatible manner.

We should split this task into two separate smaller ones, because deserializer

1. Backwards incompatible changes:

* [x] - Disallow empty fields
* [x] #4698 (postponed till Dijkstra era)

2. Future compatibility. Add alternative and more appropriate usage of:

* [x] - Maps. Done in: #4040
* [x] - Sets. Done in: #4003 

Witnesses CDDL in the end for Conway should read:

```
transaction_witness_set =
  { ? 0: nonempty_set<vkeywitness>
  , ? 1: nonempty_set<native_script>
  , ? 2: nonempty_set<bootstrap_witness>
  , ? 3: nonempty_set<plutus_v1_script>
  , ? 4: nonempty_set<plutus_data>
  , ? 5: [+ redeemer ] / { + [ tag: redeemer_tag, index: uint ] => [data: plutus_data, ex_units: ex_units ] }
  , ? 6: nonempty_set<plutus_v2_script>
  , ? 7: nonempty_set<plutus_v3_script>
  }
```

**Comment by lehins** [comment]
#3933 took care of some parts of this ticket that were possible with the current setup.

* empty fields are no longer allowed
* duplicate plutus scripts are not allowed either
* plutus scripts have an optional set tag.


This is the current CDDL:
```
transaction_witness_set =
  { ? 0: [+ vkeywitness ]
  , ? 1: [+ native_script ]
  , ? 2: [+ bootstrap_witness ]
  , ? 3: nonempty_set<plutus_v1_script>
  , ? 4: [+ plutus_data ]
  , ? 5: [+ redeemer ]
  , ? 6: nonempty_set<plutus_v2_script>
  , ? 7: nonempty_set<plutus_v3_script>
  }
```

This means that we still need to fix theses fields: `0`, `1`, `2`, `4`, `5`.

**Comment by lehins** [comment]
Closing as Done. One part of it was converted into an issue and postponed till Dijkstra #4698
