### ISSUE TITLE
Collection of things to be cleaned up after release of Conway 

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4085]
Things to cleanup:

* [x] - #5260 - Removal of `TriesToForgeADA` for Allegra https://github.com/IntersectMBO/cardano-ledger/blob/b71cb8b155268fce6ac7cf166ae0e485579d264e/eras/allegra/impl/src/Cardano/Ledger/Allegra/Rules/Utxo.hs#L112

* [x] - #5260 - Removal of `TriesToForgeADA` for Alonzo https://github.com/IntersectMBO/cardano-ledger/blob/b71cb8b155268fce6ac7cf166ae0e485579d264e/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L163-L164
* [x] - Remove complex check in plutus evaluation https://github.com/IntersectMBO/cardano-ledger/blob/b71cb8b155268fce6ac7cf166ae0e485579d264e/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/Evaluate.hs#L153-L156
* [ ] - Fix injection to use `OutputBootAddrAttrsTooBig` https://github.com/IntersectMBO/cardano-ledger/blob/b71cb8b155268fce6ac7cf166ae0e485579d264e/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L740
* [ ] - Remove all predicate failures for rules that run on the epoch boundary and replace their `PredicateFailure` with `VoidEraRule`: https://github.com/IntersectMBO/cardano-ledger/issues/4158
* [x] - #5260 - Change `OutputTooBigUTxO` predicate failure to contain `Int`, instead of `Integer`: https://github.com/IntersectMBO/cardano-ledger/blob/2c9ba10d085331fa99840a63b40b8e8b716fba5d/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L163-L164
* [x] - #5260 - Ensure no Imp test is executed with `withCborRoundTripFailures` and delete this helper function. Serialization for older predicate failures can be fixed now

**Comment by lehins** [comment]
Also #3972 falls into the same category
